version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wpp
    ports:
      - "5432:5432"

volumes:
  pgdata: